### ISSUE TITLE
RemoteCertificateNameMismatch With Wildcard Certificate on 0.15.0

### ISSUE THREAD

**Issue by FNJ5** [kerryjiang/WebSocket4Net#105]
I have a working application using WebSocket4Net 0.14.0, but need to have TLS1.2 support. I updated to the 0.15.0 DLL and now I cannot connect to my sever, getting a RemoteCertificateNameMismatch error. Did some digging into the CAPI2 logs in the Event Viewer, and I am getting a corresponding error message "The certificate's CN name does not match the passed value.". I believe version 0.15.0 introduced a bug with wildcard certificates.

I would be happy to provide any additionally information to help resolve this issue!

**Comment by kerryjiang** [comment]
Which platform's assembly do you use?
.netstandard?

**Comment by FNJ5** [comment]
We are using .NET Framework 3.5

**Comment by kerryjiang** [comment]
Could you tell me your websocket server's address? Let me write a test case for it.

**Comment by FNJ5** [comment]
I've sent you an email with the requested information.

**Comment by kerryjiang** [comment]
I did a fix already. But you also can work around this issue by setting AllowMisMatchCertificate.

using SuperSocket.ClientEngine;

client.Security.AllowNameMismatchCertificate = true;

**Comment by FNJ5** [comment]
Updated the WebSocket4Net dependency SuperSocket.ClientEngine.Core to v0.8.0.14 and the issue has been resolved!

Really appreciate your help, thanks!
