### ISSUE TITLE
Why is WebSocket4Net client closing socket with 1011 error?

### ISSUE THREAD

**Issue by CaledoniaProject** [kerryjiang/WebSocket4Net#159]
I have a python3 websocket server and a WebSocket4Net client.

During tests, the csharp client always closes in ~30s, and the python server complains like this: 

```
code = 1006 (connection closed abnormally [internal]), no reason
```

From wireshark I can tell the socket close is initiated from the client,

![screen 2019-09-13 at 17 34 37](https://user-images.githubusercontent.com/1357701/64853006-1682af80-d64d-11e9-92ec-4a495cc2e8f8.jpg)

And nodejs client `wscat` works fine:

```
%> wscat -n -c ws://192.168.154.200:11111
connected (press CTRL+C to quit)
received PING
>
```

So it's definitely a WebSocket4Net issue. I've looked through the whole repository, there's no where closing the socket with `1011` error code, can you help?

**Comment by CaledoniaProject** [comment]
For anyone experiencing this issue, use https://github.com/sta/websocket-sharp instead. WebSocket4Net is no longer under active development, sigh.

**Comment by silentcr** [comment]
thank you for remind us
