### ISSUE TITLE
Not work with domain

### ISSUE THREAD

**Issue by ghost** [kerryjiang/WebSocket4Net#172]
For some reason in linux it is not connecting if you define a domain, but if you define an ip it works normally.
No error is triggered and keeps connecting endlessly

I tried to use the pure ip, but I needed access to the "Host" header, but when it doesn't work, because it is set automatically

What can I do to resolve? It would be interesting if I could modify the "Host" header ...

_I'm sorry, I don't speak english_

**Comment by kerryjiang** [comment]
Please try WebSocket4Net latest beta release:
https://www.nuget.org/packages/WebSocket4Net/1.0.0-beta.4
