### ISSUE TITLE
中文出现乱码

### ISSUE THREAD

**Issue by hsxyhao** [kerryjiang/WebSocket4Net#174]
接收到中文数据出现了乱码：
想通过DataReceived来解决乱码问题，但是DataReceived一直没有接收数据，请教一下该怎么样解决乱码这个问题，还是说服务器传过来的数据有问题（ps: 使用Java的话没有乱码问题）！

**Comment by kerryjiang** [comment]
How do you decode binary data to string? Which encoding do you use?

**Comment by hsxyhao** [comment]
> How do you decode binary data to string? Which encoding do you use?

I'm connected to someone else's websocket server. I don't know which encoding they use. Can I use DataReceived to solve the problem? Sorry, my poor English.

**Comment by kerryjiang** [comment]
What you can get from the event DataReceived is binary data, right? You should use the same encoding which is used by the server. How do you convert the binary data to string?

**Comment by hsxyhao** [comment]
> What you can get from the event DataReceived is binary data, right? You should use the same encoding which is used by the server. How do you convert the binary data to string?

yes, i know. but the DataReceived event don't invoke. Are there some docs about DataReceived here? I don't know how to use DataReceived. 
thank you.

**Comment by kerryjiang** [comment]
But  how do you know "中文出现乱码"?

**Comment by hsxyhao** [comment]
> But how do you know "中文出现乱码"?

the result contains "��" character, thank you for answer, I will look for another solution.
