### ISSUE TITLE
Websocket client refuses to connect to a Glitch project websocket server

### ISSUE THREAD

**Issue by Andrew-Eathan** [kerryjiang/WebSocket4Net#175]
I'm not entirely sure if this is on my end, but i've tried everything and i've tested a lot to come to this conclusion.
Detailing the issue:
I have a C# project where i connect to a websocket server i host on my Glitch project. (Glitch is a hosting site)
For some reason, trying to use Websocket4Net with Glitch specifically always fails.

The reason it might be relevant is this:
When i try connecting with Websocket4Net to the Glitch server, it doesn't work.
When i try connecting with another service/library (browser websocket, or SuperSocket on another project) to the server, it works.
When i try connecting with Websocket4Net to a non-Glitch server, it seems to work.

I can provide code samples aswell.
If i'm missing something here or it's something wrong on the Glitch server end, i'm really sorry, but i just want to comfirm if this is from Websocket4Net or not.

**Comment by kerryjiang** [comment]
Please try WebSocket4Net 1.0.0-beta.2.
https://www.nuget.org/packages/WebSocket4Net/1.0.0-beta.2
