### ISSUE TITLE
"It" is websocket implementation - great, but how to start?

### ISSUE THREAD

**Issue by dylanh724** [kerryjiang/WebSocket4Net#176]
This looks great! However, there are no releases and the src is mixed with countless directories with a README that says what it is, but doesn't tell me how to quickstart.

Is there a guide? Some type of direction? There's no map~

If I have an existing implementation of Native websocket, where do I begin to swap it out with this?

**Comment by kerryjiang** [comment]
You can follow the code in unit tests.
And there are some pieces of sample code in README.
