### ISSUE TITLE
Can't connect with wss

### ISSUE THREAD

**Issue by Hanshan8023** [kerryjiang/WebSocket4Net#178]
Hi :

  I use this code to connect a wss address. But doesn't work!
  `ws_data = new WebSocket4Net.WebSocket("wss://premws-pt3.365pushodds.com/zap/?uid=1797149192385");`
  executed code, I got an exception:
   
> WebSocket_Error System.Security.Authentication.AuthenticationException: .......

**Comment by kerryjiang** [comment]
What's the message of this exception?

**Comment by Hanshan8023** [comment]
WebSocket_Error System.Security.Authentication.AuthenticationException: 调用 SSPI 失败，请参见内部异常。 ---> System.ComponentModel.Win32Exception: 要求的函数不受支持
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   在 System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   在 SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)
   在 System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   在 System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   在 SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)
WebSocket_Closed
