### ISSUE TITLE
main branch, in WebSocket.OpenAsync() method

### ISSUE THREAD

**Issue by jason-shi** [kerryjiang/WebSocket4Net#179]
public async ValueTask<bool> OpenAsync(CancellationToken cancellationToken = default)
        {
            ....
            var (key, acceptKey) = MakeSecureKey();
            await this.Channel.SendAsync((writer) => WriteHandshakeRequest(writer, key));
            ....
        }

       "this.Channel" the channel always be null when run the TestCode.

**Comment by kerryjiang** [comment]
How come the test case can go through?

**Comment by kerryjiang** [comment]
Ok, the test cases don't work correctly. Let me look into this problem.

**Comment by kerryjiang** [comment]
This bug has been fixed already.
