### ISSUE TITLE
Why does my socket always close after "41"?

### ISSUE THREAD

**Issue by 1337vida** [kerryjiang/WebSocket4Net#181]
Hello! I'm making a program that uses WebSocket4Net to connect to a socket.io server ( i made pinging stuff etc ), but it always seems to close by the client side after the 41 message. Why?

**Comment by mantasdaskev** [comment]
same problem here. I use newest nugget version 0.15.2 (which is quite old by this time, but it is official).  It just closes the conn after about 40-50s. Tried to make interval for 24h, tried turning autoping off, nothing seems to change it. It does what it wants.

**Comment by am185475** [comment]
+1 same issue.

**Comment by kerryjiang** [comment]
Please try WebSocket4Net 1.0.0-beta.2.
https://www.nuget.org/packages/WebSocket4Net/1.0.0-beta.2
