### ISSUE TITLE
How can i use library in C # asp.net MVC?

### ISSUE THREAD

**Issue by RssFra97** [kerryjiang/WebSocket4Net#184]
I would need to use the bees in Asp.net MVC when I open a page the bees I have to start reading the websockets that come from a bot automatically, as in the link where they did it in javascript, how can I do?

https://dev.streamlabs.com/docs/socket-api

I have to reproduce the same thing it does in the link, but instead of writing to the console it writes to a file to create a log of the events received

**Comment by kerryjiang** [comment]
Yes, you can.
