### ISSUE TITLE
Websocket is closed immediately after opening on Android

### ISSUE THREAD

**Issue by tungntEmotiv** [kerryjiang/WebSocket4Net#189]
Hi @kerryjiang ,

The Websocket4Net is great library for websocket project. I have built a unity project on desktop use this library. Everything work well. But when i try to build my project for android( Redmi Note 10) . The websocket is opened but closed immediately without any error. Please see my configuration as below
`
_wSC = new WebSocket("wss://localhost:12345");
  _wSC.Security.AllowUnstrustedCertificate = true;
  _wSC.Security.AllowNameMismatchCertificate = true;

  _wSC.Opened += new EventHandler(WebSocketClient_Opened);
  _wSC.Error += new EventHandler<SuperSocket.ClientEngine.ErrorEventArgs>(WebSocketClient_Error);
  _wSC.Closed += WebSocketClient_Closed;
  _wSC.MessageReceived += WebSocketClient_MessageReceived;
  _wSC.DataReceived += WebSocketClient_DataReceived;
`
I don't the configuration is enough. Could you help me ? Thanks

**Comment by kerryjiang** [comment]
Please try WebSocket4Net 1.0.0-beta.2.
https://www.nuget.org/packages/WebSocket4Net/1.0.0-beta.2
