### ISSUE TITLE
Ticket-Based authentication

### ISSUE THREAD

**Issue by ronaldowww** [kerryjiang/WebSocket4Net#191]
We are using the WebSocket4Net 0.15.2.11, and it seems that we cannot connect to the server with the URL containing the ticket query string. But the Chrome extension Simple WebSocket Client can work. 

Do you have any suggestions? Thanks in advance.

**Comment by kerryjiang** [comment]
You better try the latest 1.0 beta.
https://www.nuget.org/packages/WebSocket4Net/1.0.0-beta.4
