### ISSUE TITLE
nuget 上的 WebSocket4Net 0.15.2 看起来不是 master 版本 ？

### ISSUE THREAD

**Issue by kklldog** [kerryjiang/WebSocket4Net#192]
hi，
我从nuget上拉了 0.15.2 的包，但是看起来跟 master 版本上的代码不太一致。比如没有 receiveasync 方法 等。
是不是master版本没有编译后推送到 nuget 上 ？

**Comment by shabby2333** [comment]
master分支是非稳定版 整体用supersocket4重构的版本
0.15.2 对应 0.15分支

**Comment by kklldog** [comment]
知道了，谢谢。
