### ISSUE TITLE
Security vulnerability requires upgrading System.Net.Security to 4.3.2 or later

### ISSUE THREAD

**Issue by murjev** [kerryjiang/WebSocket4Net#194]
Current version uses System.Net.Security 4.3.0, through SuperSocket 2.0.0-beta8 which is vulnerable ref: https://github.com/aspnet/Announcements/issues/239

To address, update to using SuperSocket which uses System.Net.Security to 4.3.2 or newer.

**Comment by murjev** [comment]
This 3rd party vulnerability continues to be highlighted on scans, could you set an ETA for it?

**Comment by SpencerBurgess** [comment]
@murjev I have also seen this on scans, particularly for iOS

**Comment by kerryjiang** [comment]
Should not have this problem right now.

**Comment by kerryjiang** [comment]
Ok, I think it came from old websocket4net for .net framework.

**Comment by kerryjiang** [comment]
Won't fix it in old version. Please reference the newer version of System.Net.Security in your project by yourself.
