### ISSUE TITLE
MASK might not be set properly

### ISSUE THREAD

**Issue by realcoloride** [kerryjiang/WebSocket4Net#202]
Hello again,

It seems like when I try to connect websocket servers based on the node/javascript version of websocket, I get issues whenever a peer connects to the server.

![image](https://github.com/user-attachments/assets/98a56d79-5eb0-4dec-874e-ee6aa58f11af)

This occurs when Sending any kind of message. I presume this is a mask issue but I don't exactly how to go about resolving this, since this is not an issue with the websocketserver from node/javascript.

Cheers

**Comment by kerryjiang** [comment]
I am working on a fix for this masking issue.

**Comment by kerryjiang** [comment]
THis has been fixed in lates 1,.0 beta:
https://www.nuget.org/packages/WebSocket4Net/1.0.0-beta.4
