### ISSUE TITLE
WebSocket4Net  Visual Basic 2010

### ISSUE THREAD

**Issue by guhaizhous** [kerryjiang/WebSocket4Net#21]
Hi kerry,
 
  Now the demand, in the project I want to Visual Basic code using WebSocket4Net, the code as follows
       Imports WebSocket4Net
　　Dim websocket As New JsonWebSocket("ws://localhost:8168")
        websocket.Open()
        websocket.Send("connection", "msg")
      This does not report any errors，The server has not received any messages!
 Could you take a look, thanks very much.

**Comment by kerryjiang** [comment]
Please don't send any message until the Opened event is fired.
