### ISSUE TITLE
Migrating to Unified API

### ISSUE THREAD

**Issue by speier** [kerryjiang/WebSocket4Net#27]
Is that possible to migrate the Xamarin iOS component to the unified API? Thanks!
https://components.xamarin.com/feb-2015-ios-64-update

**Comment by larsmathiesen** [comment]
Can we expect a version that works with Xamarin iOS unified API?
http://developer.xamarin.com/guides/cross-platform/macios/updating-apps/

**Comment by kerryjiang** [comment]
I'll try to upgrade to the latest Xamarin and create an test Unified API project, then I'll give you an estimation.

**Comment by kerryjiang** [comment]
I have created a solution for iOS Unified API, WebSocket4Net.iOS.sln.
You can build it by yourself.

**Comment by speier** [comment]
Great, thanks!

**Comment by jesperll** [comment]
Hi, any chance of a NuGet package with unified support anytime soon? Don't mind if it's labeled prerelease

**Comment by kerryjiang** [comment]
Who call tell me whether this kind support works?
If yes, I can updated the package ASAP.

**Comment by mattleibow** [comment]
It works, a colleague of mine used it along with EngineIoClientDotNet and SocketIoClientDotNet for an iOS app. If we can get a release out, even if it's just prerelease, then we can update the EngineIoClientDotNet to support the Unified API.

**Comment by kerryjiang** [comment]
It seems I should release a package on this weekend.

**Comment by mattleibow** [comment]
Just wanted to see about https://github.com/kerryjiang/SuperSocket.ClientEngine/pull/7 - this is causing conflicts with the `ConcurrentQueue` type in Xamarin.iOS. Will it be possible to merge that into the references for this repo? The `ConcurrentQueue` would also be removed from the Unified project as well.

Thanks, this is much appreciated.

**Comment by kerryjiang** [comment]
Hello all, I have updated WebSocket4Net in NuGet and Xamarin Component Store.

**Comment by mattleibow** [comment]
@kerryjiang There seems to be a problem with the new iOS assemblies. They include JSON.NET - this causes conflicts and possible compilation errors. Was the inclusion of JSON.NET intentional?

**Comment by kerryjiang** [comment]
Does it cause conflicts with your own JSON.NET reference?

**Comment by mattleibow** [comment]
It does. Thanks for the update by the way.

**Comment by mattleibow** [comment]
It seems to just be Xamarin.iOS, the others are fine

**Comment by mattleibow** [comment]
You can just add a NuGet dependency on JSON.NET, although why do you use JSON.NET for iOS, but monotouch you make use of System.Runtime.Serialization.Json? Both iOS are very similar, except for a few namespaces and members, none of which you will use for this library.

**Comment by kerryjiang** [comment]
But in the iOS Unified API, I cannot find System.Runtime.Serialization.Json.
Probably I can have refactory to get rid of the third-part JSON library.
Do you have any good idea?

**Comment by mattleibow** [comment]
Ah, darn. I see now. That stuff is in the System.Runtime.Serialization framework reference. Here is the PR for that: https://github.com/kerryjiang/WebSocket4Net/pull/36

**Comment by kerryjiang** [comment]
I found it just now too, thanks!
