### ISSUE TITLE
ArgumentOutOfRangeException - ParseMimeHeaders

### ISSUE THREAD

**Issue by fbth** [kerryjiang/WebSocket4Net#28]
I'm getting an error in Extensions.cs, ParseMimeHeader function, when the line variable does not contain a colon. 

int pos = line.IndexOf(m_Colon); //looks for location of colon value
                                                         //line =   string without a colon

Since there is no colon in the line variable, the pos equals -1 after the indexOf operation.

 string key = line.Substring(0, pos); //throws exception since pos is -1

**Comment by kerryjiang** [comment]
I did a fix just now.Could you have a try?

**Comment by fbth** [comment]
I did testing and your fix appears to have resolved the issue. Thank you very much!
