### ISSUE TITLE
Please update nuget

### ISSUE THREAD

**Issue by LukePulverenti** [kerryjiang/WebSocket4Net#29]
Our Media Browser project has a number of apps that are affected by this issue:

https://github.com/kerryjiang/WebSocket4Net/pull/26

The apps range from Windows desktop to Windows Phone to Windows Store apps.

https://github.com/MediaBrowser

Thanks!

**Comment by kerryjiang** [comment]
Ok, I'll do a push to NuGet next week.

**Comment by LukePulverenti** [comment]
Thanks!

**Comment by viovanov** [comment]
Any news on this? Looking forward to the #26 fix as well.

Thank you!

**Comment by jabbera** [comment]
Any update on this? Thanks.

**Comment by kerryjiang** [comment]
I have done a update on the NuGet website, please help test it.

**Comment by jabbera** [comment]
Looks good to me.
