### ISSUE TITLE
Maybe a bug on JsonWebSocket Constructor

### ISSUE THREAD

**Issue by nathannau** [kerryjiang/WebSocket4Net#31]
In file "WebSocket4Net/WebSocket4Net/JsonWebSocket.cs" on lines 106-107 i think you want write :
> if (websocket.State **!=** WebSocketState.None)
>     throw new ArgumentException("**The** websocket must be in the initial state.", "websocket");

**Comment by kerryjiang** [comment]
You should be right.

**Comment by kerryjiang** [comment]
Fixed it just now.
https://github.com/kerryjiang/WebSocket4Net/commit/1103c36e7895c105d54c3a5321303f3082475f47
Thanks for your finding!
