### ISSUE TITLE
Option to ignore SSL certificate hostname mismatch

### ISSUE THREAD

**Issue by supermihi** [kerryjiang/WebSocket4Net#46]
Hi all,

in my testing environment, I am required to establish a wss:// connection to a test server with a self-signed SSL certificate. The connection goes through an SSH tunnel, such that additionally the hostname in the certificate does not match the hostname in the websocket url (which is "localhost"). All this is used for a WAMP connection (see also https://github.com/Code-Sharp/WampSharp/issues/131).

Now, to ignore the certificate being self-signed, I found `WebSocket.AllowUnstrustedCertificate` to be my friend. Is there a similar switch to ignore host mismatches? If not, would it be easy to implement?

Thanks in advance
Michael

**Comment by kerryjiang** [comment]
If your assembly is debug version, the name mismatch error will be ignored automatically.
At the same time, you can use the global certificate callback to ignore this error:
ServicePointManager.ServerCertificateValidationCallback

**Comment by supermihi** [comment]
Thanks, I've tried the latter method and it works! :)
