### ISSUE TITLE
Update UWP support and publish to NuGet

### ISSUE THREAD

**Issue by joelday** [kerryjiang/WebSocket4Net#51]
Currently getting this when attempting to install it from NuGet:
WebSocket4Net 0.14.1 is not compatible with UAP,Version=v10.0.

Thanks!

**Comment by kerryjiang** [comment]
Sorry, I am still working on some enhancements of SuperSocket.ClientEngine.
After it is done, I'll start to work on WebSocket4Net.

**Comment by kerryjiang** [comment]
Can I just release a version of netstandard 1.3 (dotnet core)? It is supposed to be compatible with UWP 10.
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by kerryjiang** [comment]
I think you can use the beta version in UWP:
https://www.nuget.org/packages/WebSocket4Net/0.15.0-beta5

At the same time, you need change the UWP reference to 5.2.2:

```
"dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2"
  }
```

**Comment by joelday** [comment]
Thanks!
