### ISSUE TITLE
WebSocket close when it send auto ping.

### ISSUE THREAD

**Issue by cqsir** [kerryjiang/WebSocket4Net#52]
I use WebSocket4Net to connect "Chrome Browser" for remote debugging. I found after connect build for 1 minute, the connect will receive CLOSE event, and auto close.

By step into WebSocket4Net source code,I find once auto ping is send,the connection is closed! 

I don't know why this happend. May be the reason inside Chrome，but if  this project has error，I hope you know that and fix it.

Now I had to modify the interval of  auto ping timer to 24 hour,  to prevent connection close.
-------------------------------------
The code I modified is  inside :ChromeSession.cs
-------------------------------------
        protected internal virtual void OnHandshaked()
        {
                //... ...
                //Ping auto sending interval's default value is 60 seconds
                if (AutoSendPingInterval <= 0)
                    AutoSendPingInterval = 3600*24;//60 <---------- here ,modified!!!
                m_WebSocketTimer = new Timer(OnPingTimerCallback, ProtocolProcessor, AutoSendPingInterval * 1000, AutoSendPingInterval * 1000);
            }
//...
        }

-------------------------------------

大侠!我英语不好，不知道你看明白了没：）

**Comment by kerryjiang** [comment]
Please make sure your websocket server support ping/pong.

You also can turn off AutoSendPing in WebSocket4Net.

**Comment by cqsir** [comment]
Thanks!
