### ISSUE TITLE
Can you help to release to NuGet

### ISSUE THREAD

**Issue by mmcer** [kerryjiang/WebSocket4Net#56]
Currently, we focus on Win10 RedStone (14393)  UWP development, but cannot find the package in the NuGet.
After download the source code from Github, we get failed list in the VS2015 update3.

错误  CS0103  当前上下文中不存在名称“m_SecureProtocols”	
错误          Some packages are not compatible with UAP,Version=v10.0 (win10-arm).			
错误          Some packages are not compatible with UAP, Version = v10.0 (win10-arm-aot).	
错误          Some packages are not compatible with UAP, Version = v10.0 (win10-x64).		
错误          Some packages are not compatible with UAP, Version = v10.0 (win10-x64-aot).	
错误          Some packages are not compatible with UAP, Version = v10.0 (win10-x86).		
错误          Some packages are not compatible with UAP, Version = v10.0 (win10-x86-aot).	   
错误          System.Net.Security 4.0.0 为 UAP, Version= v10.0 上的 System.Net.Security 提供了编译时引用程序集，但没有与 win10-arm 兼容的运行时程序集。		
错误          System.Net.Security 4.0.0 为 UAP, Version= v10.0 上的 System.Net.Security 提供了编译时引用程序集，但没有与 win10-arm-aot 兼容的运行时程序集。	
错误          System.Net.Security 4.0.0 为 UAP, Version= v10.0 上的 System.Net.Security 提供了编译时引用程序集，但没有与 win10-x64 兼容的运行时程序集。		
错误          System.Net.Security 4.0.0 为 UAP, Version= v10.0 上的 System.Net.Security 提供了编译时引用程序集，但没有与 win10-x64-aot 兼容的运行时程序集。	
错误          System.Net.Security 4.0.0 为 UAP, Version= v10.0 上的 System.Net.Security 提供了编译时引用程序集，但没有与 win10-x86 兼容的运行时程序集。		
错误          System.Net.Security 4.0.0 为 UAP, Version= v10.0 上的 System.Net.Security 提供了编译时引用程序集，但没有与 win10-x86-aot 兼容的运行时程序集。	 
错误          检测到 System.Collections 的版本冲突。 
 WebSocket4Net.UWP (>= 1.0.0) -> SuperSocket.ClientEngine.Core (>= 0.8.0.3) -> System.Net.Sockets (>= 4.1.0) -> System.Net.Primitives (>= 4.0.11) -> runtime.win.System.Net.Primitives (>= 4.0.11) -> System.Collections (>= 4.0.11) WebSocket4Net.UWP (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-arm(>= 1.0.0) -> System.Collections (= 4.0.10).

**Comment by kerryjiang** [comment]
Can you try to use .net core (.net standard 1.3) version in your UWP application?

**Comment by kerryjiang** [comment]
I think you can use the beta version in UWP:
https://www.nuget.org/packages/WebSocket4Net/0.15.0-beta5

At the same time, you need change the UWP reference to 5.2.2:

```
"dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",
    "SuperSocket.ProtoBase": "1.7.0.11",
    "System.Collections.Specialized": "4.0.1"
  }
```
