### ISSUE TITLE
Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib' issue for .NET 4.0 version

### ISSUE THREAD

**Issue by kirillonufreinko** [kerryjiang/WebSocket4Net#63]
Hi,

I'm receiving following build error when compiling on pure .NET 4.0 machine with 4.0 version of WebSocket4Net 14.1.0

C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFX.targets(269, 9): error MC1000: Unknown build error, 'Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.' 

It appears (according to http://stackoverflow.com/questions/13748055/could-not-load-type-system-runtime-compilerservices-extensionattribute-from-as) that ilmerge to join SuperSocket.ClientEngine.dll and WebSocket4Net.dll was run with incorrect parameters. This is also visible when I open manifest for this assembly with ildasm:

![image](https://cloud.githubusercontent.com/assets/1777622/19724702/6697bfc0-9b8a-11e6-9691-ac902238af4c.png)

This should be System.Core in this line instead of mscorlib

Could you please re-release the 14.1 version of WebSocket4Net properly built for .NET 4.0?

**Comment by kerryjiang** [comment]
It should be fixed already.
