### ISSUE TITLE
Handshake issue - the "Upgrade" header should use lowercase ("websocket")

### ISSUE THREAD

**Issue by scolestock** [kerryjiang/WebSocket4Net#64]
In drafthybi00processor.cs  and DraftHybi10Processor.cs, the "Upgrade" header is added using the casing "WebSocket".

The RFC 6455 standard says: "The request MUST contain an |Upgrade| header field whose value
       MUST include the "websocket" keyword."

I am running into some scenarios where this casing difference is causing the handshake to not complete.  If I change the case in the files above to "websocket", everything works fine.

**Comment by kerryjiang** [comment]
Great, I'll fix it ASAP!
Thanks for your finding!

**Comment by kerryjiang** [comment]
See this commit of many days ago:
https://github.com/kerryjiang/WebSocket4Net/commit/70df1bf57f79f0d4944b8fc0003f454c498fd380

**Comment by scolestock** [comment]
Thanks!
