### ISSUE TITLE
Bind to specific LocalEndPoint

### ISSUE THREAD

**Issue by osalas891123** [kerryjiang/WebSocket4Net#65]
How can i bind my client to an specific ip address, i see a related post but i can find de LocalEndPoint property

**Comment by kerryjiang** [comment]
Please try WebSocket4Net 0.15.0-beta6, which expose a property named "LocalEndPoint".

**Comment by osalas891123** [comment]
Thanks for your quick answer

**Comment by kerryjiang** [comment]
The latest release 0.15 has supported this case.
