### ISSUE TITLE
Incorrect headers initial HTTP request

### ISSUE THREAD

**Issue by HanVertegaal** [kerryjiang/WebSocket4Net#68]
RFC 7230 states:

> Since the Host field-value is critical information for handling a
request, a user agent SHOULD generate Host as the first header field
following the request-line.

In this implementation Host is the last header field. Some servers rely on the Host field coming first.

**Comment by kerryjiang** [comment]
Did a fix for it.
https://github.com/kerryjiang/WebSocket4Net/commit/7a4efe3897dec0a76b4db4f766da3fd52f1e2d60

**Comment by HanVertegaal** [comment]
Works fine now. Thank you.
