### ISSUE TITLE
again "unknown server protocol version"

### ISSUE THREAD

**Issue by symbiotic** [kerryjiang/WebSocket4Net#8]
hi, kerryjiang

i'm trying to connect to Mt Gox using their websocket API. but Websocket4Net gives the error "unknown server protocol version", when i do WebSocket.Open().

i saw that someone else ("shlomiw") also posted this problem. he mentioned that the origin should be "Origin: http://websocket.mtgox.com" and not "Origin: websocket.mtgox.com". the rfc 6455 that you told him you were going to look at confirms this too, in its examples.

can you look into this?

i'm connecting to Mt Gox with the following code:

```
WebSocket ws;

public Form1() // form constructor
{
    InitializeComponent();

    ws = new WebSocket("ws://websocket.mtgox.com/mtgox");
    ws.Opened += new EventHandler(ws_opened);
    ws.MessageReceived += new EventHandler<MessageReceivedEventArgs>(ws_message);
    ws.Error += new EventHandler<SuperSocket.ClientEngine.ErrorEventArgs>(ws_error);
    ws.Closed += new EventHandler(ws_closed);
}

private void btnTest_Click(object sender, EventArgs e)
{
    ws.Open();
}

private void ws_error(object sender, SuperSocket.ClientEngine.ErrorEventArgs e)
{
    SetMessage("error");
}
```

**Comment by ilCosmico** [comment]
Hi guys,

I get the same error trying to connect to the following webservice:

ws = new WebSocket("ws://ews.devdept.com/V1/Eyeshot.svc", "http://ews.devdept.com/V1/)
Any hints, please?

(I'm using .NET 4.5 on Windows 7 32bits)
