### ISSUE TITLE
0.15 version release date?

### ISSUE THREAD

**Issue by pscraire** [kerryjiang/WebSocket4Net#83]
Hello,

Do you know when the version 0.15 will end the beta and become an official release?

**Comment by kerryjiang** [comment]
I have released a new beta many days ago:
https://www.nuget.org/packages/WebSocket4Net/0.15.0-beta9

Could you help me to test it?

After I get enough positive feedback, I'll make a stable release.

**Comment by withakay** [comment]
Hi,

Is a stable release expected soon, or are you still waiting for more feedback on the beta?

Thanks

**Comment by mattheworiordan** [comment]
> After I get enough positive feedback, I'll make a stable release.

@kerryjiang we have been using it, seems good.  We need a stable release though before we can roll out more widely.

**Comment by kerryjiang** [comment]
Ok, I'll make a stable release on these days to celebrate the labor day. :)

**Comment by mattheworiordan** [comment]
@kerryjiang you're a legend, thanks 👍

**Comment by mattheworiordan** [comment]
Hey @kerryjiang.  How are you getting on with the release?  Any ETA?

**Comment by kerryjiang** [comment]
Hello guys,

I released WebSocket4Net 0.15 just now:
https://www.nuget.org/packages/WebSocket4Net/0.15.0
