### ISSUE TITLE
Duplicate file conflicts with System.* assemblies from 0.8.0.6 reference to SuperSocket

### ISSUE THREAD

**Issue by berdon** [kerryjiang/WebSocket4Net#88]
See https://github.com/kerryjiang/SuperSocket.ClientEngine/issues/61

Note: This is specific to the v0.15.0-beta6 nuget package.

**Comment by kerryjiang** [comment]
It should have been fixed by the new release beta version https://www.nuget.org/packages/WebSocket4Net/0.15.0-beta7

Could you try it?
