### ISSUE TITLE
Connection refused on Andriod

### ISSUE THREAD

**Issue by celerite** [kerryjiang/WebSocket4Net#89]
All,
from IOS we are able to connect the websocket client to the server fine, but when we run on andriod the error is "{System.Net.Sockets.SocketException (0x80004005): Connection refused}"
but the port is open
telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^CConnection closed by foreign host.

**Comment by kerryjiang** [comment]
Where is the server side running?
In the android or the host machine?

**Comment by celerite** [comment]
running locally. If I run the IOS sim it connects fine just when I run the Andriod one it gives that error. So same code.

**Comment by kerryjiang** [comment]
So do you mean your server is running in your host machine?

**Comment by celerite** [comment]
Yes

**Comment by kerryjiang** [comment]
So are your iOS and android running in simulator?

**Comment by celerite** [comment]
Yes I have Xamarin running so I get both. IOS sim is good code works and connects. Andriod tho just gives that error.

**Comment by kerryjiang** [comment]
These are my suggestions:

1) verify the connectivity from inside the android simulator;
2) try to connect another open websocket server;

**Comment by celerite** [comment]
Let me try that, don't understand how IOS Sim is able to connect using the same code. How do I check using the Andriod sim?

**Comment by celerite** [comment]
Interesting apologies 127.0.0.1 will not work you have to use the IP address of your host.
