### ISSUE TITLE
Issue while creating WebSocket server on Azure VM

### ISSUE THREAD

**Issue by SasiPhanindra** [kerryjiang/WebSocket4Net#90]
We are trying to create a WebSocket server with WebTrends SAPI Stream (“**wss://sapi.webtrends.com/streaming**”) on one of the Azure Servers.
We are facing following error while trying to open the socket. 
    
‘{"Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."}’

However, it is working fine with “**ws://sapi.webtrends.com/streaming**” (Not Secure Version)

Code:
    websocket = new WebSocket("wss://sapi.webtrends.com/streaming");
    websocket.Opened += new EventHandler(Websocket_Opened);
    websocket.Error += Websocket_Error;
    websocket.Closed += new EventHandler(Websocket_Closed);
    websocket.MessageReceived += Websocket_MessageReceived;
    websocket.AutoSendPingInterval = 1;
    websocket.Open();

We have found that the Security Protocol which is being used on the servers where this code is working is TLS 1.2 whereas it TLS 1.0 in this server. So, we hard coded to set the security protocol before making the API call.
        **System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;**
        websocket = new WebSocket("wss://sapi.webtrends.com/streaming");
        websocket.Opened += new EventHandler(Websocket_Opened);
        websocket.Error += Websocket_Error;
        websocket.Closed += new EventHandler(Websocket_Closed);
        websocket.MessageReceived += Websocket_MessageReceived;
        websocket.AutoSendPingInterval = 1;
        websocket.AllowUnstrustedCertificate = true;
        websocket.Open();

But that didn't resolve the issue. Any kind of help would be greatly appreciated.

**Comment by kerryjiang** [comment]
Did you find anything from the server's logs?

**Comment by SasiPhanindra** [comment]
Following is the stack trace in Event Viewer

Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Stack Trace:    at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)

**Comment by danders32** [comment]
We wrote a basic .NET app that does an HTTP GET operation for "https://www.bing.com". As per network traces, client and server were communicatig over TLS 1.2 protocol.

1241	5:46:40 PM 5/19/2017	7.7596882	System	myIPaddress	any.edge.bing.com	TLS	TLS:TLS Rec Layer-1 HandShake: Client Hello.	{TLS:50, SSLVersionSelector:49, TCP:47, IPv4:46}

16 03 03 00 AB ....

1244	5:46:40 PM 5/19/2017	7.7629077	System	any.edge.bing.com	myIPaddress	TLS	TLS:TLS Rec Layer-1 HandShake: Server Hello. Certificate.	{TLS:50, SSLVersionSelector:49, TCP:47, IPv4:46}

16 03 03 13 68 ....

-> For basic .NET App, it directly picked TLS 1.2 - we did not have to tell it to as TLS 1.2 is the default protocol for server 2012 R2 OS.

However, when we ran the WebSocket4Net based app, clientHello was still over TLS 1.0 and server was not happy for the reason that it expects TLS 1.2 in clint hello.

2046	5:55:33 PM 5/19/2017	5.8170552		myIPaddress	serverhostname	TLS	TLS:TLS Rec Layer-1 HandShake: Client Hello.	{TLS:34, SSLVersionSelector:33, TCP:30, IPv4:29}

16 03 01 00 81  ....

2047	5:55:33 PM 5/19/2017	5.8401012		serverhostname	myIPaddress	TCP	TCP:Flags=...A.R.., SrcPort=HTTPS(443), DstPort=19042, PayloadLen=0, Seq=2097237200, Ack=3220597356, Win=9818 (scale factor 0x0) = 9818	{TCP:30, IPv4:29}

TCP RESET

Question
=============
For WebSocket4Net based apps, how can it be aware that it should TLS1.2 protocol in ClientHello? If we can manage that, our problem is solved.

**Comment by kerryjiang** [comment]
Which version do you use? In the latest beta version, it support specifying the TLS protocol version.
 Try out the Security option of the WebSocket4Net.

**Comment by danders32** [comment]
We were using the latest stable version from Nuget. Just installed the beta version. 

Is the below what you are referring to?

websocket = new WebSocket("wss://sapi.webtrends.com/streaming", sslProtocols: SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls);

**Comment by kerryjiang** [comment]
Yes, you can.
Tell me if it works for you!

**Comment by SasiPhanindra** [comment]
Thank you keeryjiang.
It seems to be working fine😊.  Will let you know if we need any further help.
