### ISSUE TITLE
dotnet core supported or not?

### ISSUE THREAD

**Issue by TroelsL** [kerryjiang/WebSocket4Net#95]
I'm slightly confused. The project page states that .NET Core is supported, and I can see a directory in the source to indicate the same, but installing the NuGet package yields:

    Restoring packages for c:\Users\xxx\Documents\Visual Studio 2017\Projects\smarthome\Asgard.Kodi.Api\src\Asgard.Kodi.Api\Asgard.Kodi.Api.csproj...
    Package WebSocket4Net 0.14.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package 
    WebSocket4Net 0.14.1 supports:
      - monoandroid23 (MonoAndroid,Version=v2.3)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - sl4 (Silverlight,Version=v4.0)
      - sl5 (Silverlight,Version=v5.0)
      - sl5-wp (Silverlight,Version=v5.0,Profile=WindowsPhone)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.1.
    Package restore failed. Rolling back package changes for 'Asgard.Kodi.Api'.
    Time Elapsed: 00:00:02.1456436
    ========== Finished ==========

Am I missing something, or will I need to compile from source?

**Comment by kerryjiang** [comment]
Please use the latest beta version 0.15.0-beta8:
https://www.nuget.org/packages/WebSocket4Net/0.15.0-beta8

**Comment by TroelsL** [comment]
Ah, excellent. Missed that, thanks!

And the client actually fixed my hard-to-debug issue of getting an "One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)" exception when deploying my solution to docker.

This client saved me hours of excruciating work, thanks!
