### ISSUE TITLE
Getting 401 when connecting

### ISSUE THREAD

**Issue by BIERAAP** [kerryjiang/WebSocket4Net#96]
Getting a System.Exception: HTTP/1.1 401 Unauthorized when connecting.

websocketClient = new WebSocket(this.url, sslProtocols: SslProtocols.Tls12 | SslProtocols.Tls11);

There is no authentication required by the server.
Any idea how to solve?

Using a ClientWebSocket works without a problem. ;(

using the latest beta..

**Comment by kerryjiang** [comment]
Could you tell me the target websocket url and which version of WebSocket4Net do you use?

**Comment by BIERAAP** [comment]
For some reason my firewall was blocking the request. Made some adjustments to the firewall and everything is working now.

**Comment by kerryjiang** [comment]
Good to know it. Thank you!
